"""Test quality inspection with real report_agent output format.

This test simulates importing a report generated by report_agent and performs
quality inspection according to the actual ReportPackage structure.
"""

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from dotenv import load_dotenv
load_dotenv()

from report_agent.models import (
    ReportPackage,
    SourceRecord,
    EvidenceCard,
    PMInsight,
    SWOTItem,
    SWOTResult,
    ProductRecommendation,
    ReportState,
)

from agent.quality_agent import (
    LLMConfig,
    QualityConfig,
    InspectionMode,
    inspect_report_package,
)


def create_realistic_report_package(task_id: str = "test_report") -> ReportPackage:
    """Create a realistic report package that mimics actual report_agent output."""
    
    # Step 1: Create SourceRecords (from search results)
    sources = [
        SourceRecord(
            source_id="src_001",
            title="Cursor AI - AI-Powered Code Editor",
            url="https://cursor.com/features",
            snippet="Cursor AI provides real-time code completion with GPT-4 integration",
            content="Cursor is an AI-first code editor that leverages GPT-4 to provide intelligent code suggestions, real-time completion, and chat-based code assistance. It supports 30+ programming languages and integrates with GitHub.",
            source="Official Website",
            content_source="cursor.com",
            publish_date="2024-03-15",
            credibility_score=0.95,
        ),
        SourceRecord(
            source_id="src_002",
            title="GitHub Copilot Pricing and Features",
            url="https://github.com/features/copilot",
            snippet="GitHub Copilot costs $10/month with free trial available",
            content="GitHub Copilot offers AI-powered code suggestions. Individual plan is $10/month, business plan is $19/user/month. It supports all major IDEs including VS Code, JetBrains, and Neovim.",
            source="Official Website",
            content_source="github.com",
            publish_date="2024-02-20",
            credibility_score=0.98,
        ),
        SourceRecord(
            source_id="src_003",
            title="Tabnine vs Cursor vs Copilot Comparison",
            url="https://www.techradar.com/best/best-ai-code-assistants",
            snippet="Cursor leads in code understanding; Copilot has better IDE integration",
            content="In our comprehensive testing, Cursor demonstrated superior code understanding capabilities with its GPT-4 backend, while GitHub Copilot excelled in terms of IDE compatibility and ecosystem integration.",
            source="TechRadar",
            content_source="techradar.com",
            publish_date="2024-01-10",
            credibility_score=0.85,
        ),
    ]

    # Step 2: Create EvidenceCards (from evidence extraction)
    evidence_cards = [
        EvidenceCard(
            evidence_id="ev_001",
            source_id="src_001",
            competitor="Cursor",
            dimension="function",
            claim="Cursor AI supports real-time code completion with GPT-4",
            raw_excerpt="Cursor AI provides real-time code completion with GPT-4 integration",
            confidence=0.95,
            freshness="2024-03-15",
            importance_for_pm="High - core feature differentiation",
        ),
        EvidenceCard(
            evidence_id="ev_002",
            source_id="src_002",
            competitor="Copilot",
            dimension="pricing",
            claim="GitHub Copilot pricing starts at $10/month for individuals",
            raw_excerpt="Individual plan is $10/month, business plan is $19/user/month",
            confidence=0.98,
            freshness="2024-02-20",
            importance_for_pm="Medium - pricing strategy reference",
        ),
        EvidenceCard(
            evidence_id="ev_003",
            source_id="src_003",
            competitor="Cursor",
            dimension="competitive_analysis",
            claim="Cursor leads in code understanding capabilities",
            raw_excerpt="Cursor demonstrated superior code understanding capabilities",
            confidence=0.85,
            freshness="2024-01-10",
            importance_for_pm="High - competitive advantage insight",
        ),
        EvidenceCard(
            evidence_id="ev_004",
            source_id="src_003",
            competitor="Copilot",
            dimension="competitive_analysis",
            claim="Copilot excels in IDE compatibility",
            raw_excerpt="GitHub Copilot excelled in terms of IDE compatibility",
            confidence=0.85,
            freshness="2024-01-10",
            importance_for_pm="Medium - feature gap analysis",
        ),
    ]

    # Step 3: Create PMInsights
    pm_insights = [
        PMInsight(
            insight_id="ins_001",
            type="market_trend",
            title="AI code assistants gaining rapid adoption",
            description="AI-powered code assistants are becoming essential tools for developers, with Cursor and Copilot leading the market",
            related_competitors=["Cursor", "Copilot"],
            evidence_ids=["ev_001", "ev_002", "ev_003"],
            pm_value="Market opportunity exists for AI coding tools with better UX",
            confidence=0.9,
        ),
        PMInsight(
            insight_id="ins_002",
            type="competitive_gap",
            title="Cursor has edge in AI capabilities",
            description="Cursor's GPT-4 integration provides superior code understanding compared to competitors",
            related_competitors=["Cursor"],
            evidence_ids=["ev_001", "ev_003"],
            pm_value="We should consider GPT-4 integration to compete",
            confidence=0.85,
        ),
    ]

    # Step 4: Create SWOT analysis
    swot = SWOTResult(
        strengths=[
            SWOTItem(
                point="Strong AI capabilities with GPT-4",
                why_it_matters="Provides superior code understanding and suggestions",
                evidence_ids=["ev_001", "ev_003"],
                pm_implication="Continue investing in AI model improvements",
                confidence=0.9,
            ),
        ],
        weaknesses=[
            SWOTItem(
                point="Limited IDE support compared to Copilot",
                why_it_matters="May limit adoption among developers using niche IDEs",
                evidence_ids=["ev_004"],
                pm_implication="Expand IDE compatibility",
                confidence=0.8,
            ),
        ],
        opportunities=[
            SWOTItem(
                point="Growing market demand for AI coding tools",
                why_it_matters="Market expansion opportunity",
                evidence_ids=["ev_001", "ev_002"],
                pm_implication="Accelerate feature development",
                confidence=0.88,
            ),
        ],
        threats=[
            SWOTItem(
                point="Intense competition from established players",
                why_it_matters="GitHub's market position makes it hard to gain share",
                evidence_ids=["ev_002", "ev_004"],
                pm_implication="Differentiate with unique features",
                confidence=0.85,
            ),
        ],
    )

    # Step 5: Create Recommendations
    recommendations = [
        ProductRecommendation(
            priority="high",
            timeframe="30 days",
            action="Integrate GPT-4 for code understanding",
            reason="Cursor's GPT-4 integration gives them competitive advantage",
            expected_impact="Improve code suggestion quality by 30%",
            risk="Medium - API cost increases",
            evidence_ids=["ev_001", "ev_003"],
            success_metric="Code acceptance rate > 70%",
        ),
        ProductRecommendation(
            priority="medium",
            timeframe="60 days",
            action="Expand IDE support to JetBrains and Neovim",
            reason="Copilot supports more IDEs, which is a competitive advantage",
            expected_impact="Increase potential user base by 40%",
            risk="Low - standard integration patterns",
            evidence_ids=["ev_004"],
            success_metric="Support 5+ major IDEs",
        ),
    ]

    # Step 6: Build structured_analysis dict
    structured_analysis = {
        "evidence_cards": [ec.to_dict() for ec in evidence_cards],
        "pm_insights": [pi.to_dict() for pi in pm_insights],
        "comparison_tables": [
            {
                "competitor": "Cursor",
                "features": ["GPT-4", "Real-time completion", "AI chat"],
                "pricing": "$20/month",
                "rating": 4.5,
            },
            {
                "competitor": "Copilot",
                "features": ["Code suggestions", "Multi-IDE", "GitHub integration"],
                "pricing": "$10/month",
                "rating": 4.3,
            },
        ],
        "swot": swot.to_dict(),
        "recommendations": [rec.to_dict() for rec in recommendations],
        "executive_summary": {
            "competitors": ["Cursor", "Copilot", "Tabnine"],
            "market_size": "Estimated $1.2B by 2025",
            "key_findings": ["GPT-4 integration is key differentiator", "Pricing sensitivity exists"],
        },
    }

    # Step 7: Build claim_evidence_map
    claim_evidence_map = [
        {"claim_id": "clm_001", "claim": "Cursor uses GPT-4", "evidence_ids": ["ev_001"]},
        {"claim_id": "clm_002", "claim": "Copilot is cheaper", "evidence_ids": ["ev_002"]},
        {"claim_id": "clm_003", "claim": "Cursor has better AI", "evidence_ids": ["ev_003"]},
        {"claim_id": "clm_004", "claim": "Copilot has wider IDE support", "evidence_ids": ["ev_004"]},
    ]

    # Step 8: Build generation_trace
    generation_trace = [
        {"step": "search", "status": "completed", "count": 3},
        {"step": "evidence_extraction", "status": "completed", "count": 4},
        {"step": "insight_generation", "status": "completed", "count": 2},
        {"step": "swot_analysis", "status": "completed"},
        {"step": "recommendation", "status": "completed", "count": 2},
        {"step": "report_writing", "status": "completed"},
    ]

    # Step 9: Generate report markdown (simulated report_agent output)
    report_markdown = """# AI Coding Tools Competitive Analysis Report

## Executive Summary
The AI coding assistant market is rapidly growing, estimated to reach $1.2B by 2025. Key players include Cursor, GitHub Copilot, and Tabnine. Cursor's GPT-4 integration provides a competitive edge in code understanding, while Copilot leads in IDE compatibility.

## Market Overview
AI-powered code assistants have become essential tools for developers, improving productivity by automating repetitive coding tasks and providing intelligent suggestions.

## Competitive Landscape

### Cursor AI
- **AI Capabilities**: GPT-4 integration
- **Pricing**: $20/month
- **Strengths**: Superior code understanding
- **Weaknesses**: Limited IDE support

### GitHub Copilot
- **AI Capabilities**: Codex model
- **Pricing**: $10/month
- **Strengths**: Excellent IDE integration, GitHub ecosystem
- **Weaknesses**: Code quality inconsistent

## SWOT Analysis

### Strengths
- Strong AI capabilities with GPT-4 integration
- Real-time code completion feature

### Weaknesses
- Limited IDE support compared to competitors
- Higher price point

### Opportunities
- Growing market demand
- Potential for enterprise adoption

### Threats
- Intense competition from GitHub
- Rapid technological change

## Strategic Recommendations

### Short-term (30 days)
1. **Integrate GPT-4** - Priority: High
   - Reason: Cursor's GPT-4 integration gives competitive advantage
   - Expected Impact: 30% improvement in code suggestion quality

### Medium-term (60 days)
2. **Expand IDE Support** - Priority: Medium
   - Reason: Copilot supports more IDEs
   - Expected Impact: 40% increase in potential user base

## Conclusion
The AI coding assistant market presents significant opportunities. To compete effectively, we need to enhance our AI capabilities and expand platform support.

---
*Generated by Report Agent*
"""

    # Step 10: Create ReportPackage
    return ReportPackage(
        task_id=task_id,
        report_markdown=report_markdown,
        structured_analysis=structured_analysis,
        claim_evidence_map=claim_evidence_map,
        generation_trace=generation_trace,
        sources=[s.to_dict() for s in sources],
        missing_info=["Detailed feature comparison data", "Enterprise pricing information"],
        low_confidence_claims=[],
    )


def test_real_report_inspection():
    """Test quality inspection with a realistic report package."""
    print("="*70)
    print("REAL REPORT AGENT OUTPUT QUALITY INSPECTION")
    print("="*70)
    print("\n[Step 1] Creating realistic report package...")
    
    # Create a realistic report (simulating report_agent output)
    report = create_realistic_report_package(task_id="competitive_analysis_2024")
    
    print(f"  Task ID: {report.task_id}")
    print(f"  Sources count: {len(report.sources)}")
    print(f"  Evidence cards count: {len(report.structured_analysis.get('evidence_cards', []))}")
    print(f"  Report length: {len(report.report_markdown)} characters")
    print("  [OK] Report package created successfully")

    print("\n[Step 2] Configuring quality inspection...")
    print("  Mode: HYBRID_VOTING (LLM + Rules)")
    llm_key = os.getenv("LLM_API_KEY", "")
    print(f"  LLM Enabled: {bool(llm_key)} (API Key: {'***' + llm_key[-8:] if llm_key else 'NOT SET'})")

    # Configure quality inspection
    config = QualityConfig.from_env(),
        llm_model=os.getenv("LLM_MODEL", "ep-20250125"),
        inspection_mode=InspectionMode.HYBRID_VOTING,
        voting_threshold=0.6,
        voting_llm_weight=0.5,
        llm_enabled=bool(os.getenv("LLM_API_KEY", "")),
        rule_enabled=True,
        verbose=True
    )

    print("\n[Step 3] Running quality inspection...")
    result = inspect_report_package(report, config=config)

    print("\n" + "="*70)
    print("INSPECTION RESULTS")
    print("="*70)
    print(f"\n[Overall Result]")
    print(f"  Passed: {'YES' if result.passed else 'NO'}")
    print(f"  Score: {result.score:.2f}")
    print(f"  Confidence: {result.confidence_level.value}")
    print(f"  Needs human review: {'YES' if result.needs_human_review else 'NO'}")
    print(f"  Total issues detected: {len(result.issues)}")

    if result.issues:
        print("\n[Detailed Issues]")
        for i, issue in enumerate(result.issues, 1):
            print(f"\n{i}. [{issue.severity.value.upper()}] {issue.type.value}")
            print(f"   ├─ Description: {issue.description}")
            print(f"   ├─ Suggestion: {issue.suggestion}")
            print(f"   └─ Impact: {issue.impact if issue.impact else 'Not specified'}")

        print("\n[Feedback Target Analysis]")
        from agent.quality_agent.config import IssueType
        
        collector_issues = []
        analyst_issues = []
        writer_issues = []
        
        for issue in result.issues:
            if issue.type in {IssueType.INSUFFICIENT_EVIDENCE, IssueType.LOW_QUALITY_EVIDENCE, IssueType.MISSING_SOURCE}:
                collector_issues.append(issue)
            elif issue.type in {IssueType.LOGICAL_INCONSISTENCY, IssueType.INCOMPLETE_INFO}:
                analyst_issues.append(issue)
            elif issue.type in {IssueType.WEAK_EVIDENCE_SUPPORT, IssueType.CONFLICTING_EVIDENCE}:
                writer_issues.append(issue)
        
        print(f"  → Collector Agent issues: {len(collector_issues)}")
        print(f"  → Analyst Agent issues: {len(analyst_issues)}")
        print(f"  → Writer Agent issues: {len(writer_issues)}")

    print("\n" + "="*70)
    print("INSPECTION COMPLETE")
    print("="*70)


def test_edge_case_reports():
    """Test edge case reports to validate inspection robustness."""
    print("\n" + "="*70)
    print("EDGE CASE TESTS")
    print("="*70)

    # Test 1: Empty report
    print("\n[Test 1] Empty Report")
    empty_report = ReportPackage(
        task_id="empty_report",
        report_markdown="",
        structured_analysis={},
        claim_evidence_map=[],
        generation_trace=[],
        sources=[],
    )
    
    config = QualityConfig.from_env(),
        llm_model=os.getenv("LLM_MODEL", "ep-20250125"),
        inspection_mode=InspectionMode.RULE_ONLY,
        llm_enabled=bool(os.getenv("LLM_API_KEY", "")),
        rule_enabled=True,
    )
    
    result = inspect_report_package(empty_report, config=config)
    print(f"  Passed: {result.passed}, Score: {result.score:.2f}, Issues: {len(result.issues)}")

    # Test 2: Report with missing evidence
    print("\n[Test 2] Report with Missing Evidence")
    report_with_issue = create_realistic_report_package(task_id="issue_report")
    # Remove evidence mapping to create issue
    report_with_issue.claim_evidence_map = [
        {"claim_id": "clm_001", "claim": "Unsupported claim", "evidence_ids": []}
    ]
    
    result = inspect_report_package(report_with_issue, config=config)
    print(f"  Passed: {result.passed}, Score: {result.score:.2f}, Issues: {len(result.issues)}")
    
    major_issues = [i for i in result.issues if i.severity.value == "major"]
    print(f"  Major issues: {len(major_issues)}")


if __name__ == "__main__":
    test_real_report_inspection()
    test_edge_case_reports()
    
    print("\n" + "="*70)
    print("ALL TESTS COMPLETED")
    print("="*70)